pipeline:
  docker:
    image: plugins/docker
    repo: sboulema/linky
  deploy:
    image: appleboy/drone-ssh
    host: sboulema.nl
    username: ${SSH_USERNAME}
    password: ${SSH_PASSWORD}
    port: 22
    script:
      - sudo docker-compose -f /home/sboulema/stackfiles/Linky.yml pull
      - sudo docker-compose -f /home/sboulema/stackfiles/Linky.yml up -d
      - sudo docker-compose -f /home/sboulema/stackfiles/HaProxy.yml up -d
    when:
      status: success