resources:
- repo: self

variables:
- group: FontAwesome

queue:
  name: Hosted Ubuntu 1604

steps:
- powershell: |  
   ((Get-Content -path .npmrc -Raw) -replace '{FATOKEN}',$env:faToken) | Set-Content -Path .npmrc
   
  displayName: 'Insert FontAwesome token'
  env:
    faToken: $(fontAwesomeToken)

- powershell: |  
   ((Get-Content -path index.html -Raw) -replace '{firebaseApiKey}',$env:firebaseApiKey) | Set-Content -Path index.html
   
  displayName: 'Insert FirebaseApiKey'
  env:
    firebaseApiKey: $(firebaseApiKey)

- powershell: |  
   ((Get-Content -path webextension/js/popup.js -Raw) -replace '{firebaseApiKey}',$env:firebaseApiKey) | Set-Content -Path webextension/js/popup.js
   
  displayName: 'Insert FirebaseApiKey into WebExtension'
  env:
    firebaseApiKey: $(firebaseApiKey)

- powershell: |  
   ((Get-Content -path settings.json -Raw) -replace '{VERSION}',$env:settingsVersion) | Set-Content -Path settings.json
   
  displayName: 'Insert Version into Settings'
  env:
    settingsVersion: $(Build.BuildNumber)

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    imageName: sboulema/linky
    includeLatestTag: true

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    imageName: sboulema/linky
    includeLatestTag: true

- task: SSH@0
  displayName: 'Deploy an image'
  inputs:
    sshEndpoint: CurleezBox
    commands: /home/sboulema/deployDockerContainer Linky linky