resources:
- repo: self

variables:
- group: FontAwesome

queue:
  name: Hosted Ubuntu 1604

steps:
- powershell: |
   Write-Host $env:faToken   
   ((Get-Content -path .npmrc -Raw) -replace '{FATOKEN}','$env:faToken') | Set-Content -Path .npmrc
   Get-Content -Path .npmrc
   
  displayName: 'Insert FontAwesome token'
  env:
    faToken: $(fontAwesomeToken)

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    imageName: sboulema/linky
    includeLatestTag: true

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: 'Push an image'
    imageName: sboulema/linky
    includeLatestTag: true

- task: SSH@0
  displayName: 'Deploy an image'
  inputs:
    sshEndpoint: CurleezBox
    commands: /home/sboulema/deployDockerContainer Linky linky